# Generated by Django 4.1.4 on 2023-01-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpassword',
            name='user',
        ),
    ]
